apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: {{ include "ocp-ldap-proxy.fullname" . }}-serving-cert
  name: {{ include "ocp-ldap-proxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: ldaps
    port: 636
    protocol: TCP
    targetPort: ldaps
  selector:
    {{- include "ocp-ldap-proxy.selectorLabels" . | nindent 4 }}
  sessionAffinity: ClientIP
  type: ClusterIP
