{{- if .Values.servingCertSync.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ocp-ldap-proxy.fullname" . }}--binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ocp-ldap-proxy.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "ocp-ldap-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
