{{- if .Values.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "ocp-ldap-proxy.fullname" . }}-networkpolicy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "ocp-ldap-proxy.selectorLabels" . | nindent 6 }}
  ingress:
  - from:
    - namespaceSelector:
        {{- with .Values.networkPolicy.sourceNamespaceLabels }}
        matchLabels:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{- end }}
