apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocp-ldap-proxy.fullname" . }}-serving-ca
  namespace: {{ .Release.Namespace }}
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
data: {}
