{{- if .Values.servingCertSync.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ocp-ldap-proxy.fullname" . }}-configmap-sync-binding
  namespace: {{ .Values.servingCertSync.destinationNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ocp-ldap-proxy.fullname" . }}-configmap-sync
subjects:
- kind: ServiceAccount
  name: {{ include "ocp-ldap-proxy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
